// Solve the Temperature equation

//volScalarField div_U = fvc::div(phi, U);  

            fvScalarMatrix TEqn
            (
                fvm::ddt(T)
              + fvm::div(phi, T)
              - fvm::laplacian(DT, T)
             ==
                fvOptions(T)
            );

            TEqn.relax();
            fvOptions.constrain(TEqn);
            TEqn.solve();
            fvOptions.correct(T);



//+nu/(Cp)*div_U*div_U